version: '3.4'

services:
    catalogdb:
        container_name: catalogdb
        restart: always
        volumes:
            - mongo_data:/data/db
        ports:
            - "27017:27017"

    basketdb:
        container_name: basketdb
        restart: always
        ports:
            - "6379:6379"

    orderdb:
        container_name: orderdb
        ports:
            - "1433:1433"
        environment:
            SA_PASSWORD: "SwN12345678"
            ACCEPT_EULA: "Y"

    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    catalog.api:
        container_name: catalogapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "JWT:Security=ReadingIsGood authentication"
            - "JWT:Issuer=localhost"
            - "JWT:Audience=ReadingIsGood"
            - "CatalogDatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - catalogdb
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8000:80"
    basket.api:
        container_name: basketapi
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "JWT:Security=ReadingIsGood authentication"
            - "JWT:Issuer=localhost"
            - "JWT:Audience=ReadingIsGood"
            - "ConnectionStrings:Redis=basketdb:6379"
            - "EventBus:HostName=rabbitmq"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - basketdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8001:80"
    ordering.api:
        container_name: orderingapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "JWT:Security=ReadingIsGood authentication"
            - "JWT:Issuer=localhost"
            - "JWT:Audience=ReadingIsGood"
            - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
            - "EventBus:HostName=rabbitmq"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - orderdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8002:80"
    customer.api:
        container_name: customerapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "EventBus:HostName=rabbitmq"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - orderdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8003:80"
    auth.api:
        container_name: authapi
        restart: on-failure
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "JWT:Security=ReadingIsGood authentication"
            - "JWT:Issuer=localhost"
            - "JWT:Audience=ReadingIsGood"
            - "ConnectionStrings:OrderConnection=Server=orderdb;Database=OrderDb;User Id=sa;Password=SwN12345678;"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - orderdb
            - rabbitmq
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "8004:80"
    ocelotapigateway:
        container_name: ocelotapigateway
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - "JWT:Security=ReadingIsGood authentication"
            - "JWT:Issuer=localhost"
            - "JWT:Audience=ReadingIsGood"
            - "ElasticConfiguration:Uri=http://elasticsearch:9200"
        depends_on:
            - catalog.api
            - basket.api
            - ordering.api
            - customer.api
            - auth.api
        volumes:
            - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
            - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
            - "7000:80"

    elasticsearch:
        container_name: elasticsearch
        environment:
            - xpack.monitoring.enabled=true
            - xpack.watcher.enabled=false
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
            - discovery.type=single-node
        ports:
            - "9200:9200"
        volumes:
            - elasticsearch-data:/usr/share/elasticsearch/data   

    kibana:
        container_name: kibana
        environment:        
            - ELASTICSEARCH_URL=http://elasticsearch:9200
        depends_on:
            - elasticsearch
        ports:
            - "5601:5601"
    webstatus:
        container_name: webstatus
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - HealthChecksUI__HealthChecks__0__Name=Catalog Health Check
            - HealthChecksUI__HealthChecks__0__Uri=http://catalog.api/hc
            - HealthChecksUI__HealthChecks__1__Name=Basket Health Check
            - HealthChecksUI__HealthChecks__1__Uri=http://basket.api/hc
            - HealthChecksUI__HealthChecks__2__Name=Ordering Health Check
            - HealthChecksUI__HealthChecks__2__Uri=http://ordering.api/hc  
            - HealthChecksUI__HealthChecks__3__Name=Customer Health Check
            - HealthChecksUI__HealthChecks__3__Uri=http://customer.api/hc  
        ports:
            - "8007:80"